"""
train_dpo.py - Stage 3: DPO for conversation quality

Trains Nalana's conversational intelligence:
  - When to ask questions vs. execute immediately
  - Depth of physics/design reasoning in explanations
  - Quality of clarifying questions (specific vs. vague)
  - Tone matching and collaborative style

Data sources for DPO pairs:
  1. Execution reward pairs from train_rl.py (chosen=executed, rejected=failed)
  2. integrations/dream3d_synthetic.py DPO pairs (expert vs. basic implementations)
  3. Synthetic conversation quality pairs (generated by Claude/Qwen2.5-72B):
     - Chosen: asks ONE focused clarifying question
     - Rejected: asks 5 vague questions or just executes without understanding
  4. Physics reasoning pairs:
     - Chosen: explains IOR physics, then gives code
     - Rejected: gives code without explanation

Data format (each pair):
{
  "prompt":   "The conversation history / user request",
  "chosen":   "The better assistant response",
  "rejected": "The worse assistant response",
  "source":   "execution|dream3d|synthetic_conv|physics_reasoning",
  "weight":   1.0   // optional per-pair loss weight
}

Usage:
  python train_dpo.py --base-model checkpoints/nalana-rl/final --output-dir checkpoints/nalana-dpo
  python train_dpo.py --beta 0.1 --max-steps 1000
  python train_dpo.py --data-sources execution dream3d synthetic --data-weights 1.0 1.5 0.8

Hardware target: 18x A6000 (48GB each)
GPU allocation:
  - GPUs 0-15: DPO training (DeepSpeed ZeRO-2)
  - GPUs 16-17: Reserved for eval / generation

Launch:
  CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 \\
  deepspeed --num_gpus=16 train_dpo.py \\
    --base-model checkpoints/nalana-rl/final \\
    --output-dir checkpoints/nalana-dpo \\
    --deepspeed ds_config_rl.json
"""

import argparse
import json
import logging
import math
import os
import random
import sys
import time
from pathlib import Path
from typing import Optional

import torch
from datasets import Dataset
from peft import LoraConfig, TaskType, get_peft_model
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainerCallback,
    TrainingArguments,
)

try:
    from trl import DPOConfig, DPOTrainer
    HAS_TRL_DPO = True
except ImportError:
    HAS_TRL_DPO = False

try:
    import wandb
    HAS_WANDB = True
except ImportError:
    HAS_WANDB = False

try:
    from tqdm import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False

logging.basicConfig(
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%H:%M:%S",
    level=logging.INFO,
)
log = logging.getLogger("nalana-dpo")

ROOT = Path(__file__).parents[1]


# ─── DPO Dataset ──────────────────────────────────────────────────────────────

class DPODataset:
    """
    Loads and merges DPO preference pairs from multiple sources.

    Expected format for each source file (JSONL):
      {"prompt": str, "chosen": str, "rejected": str, "source": str, "weight": float}

    Sources:
      - execution:      Pairs from RL training (run success vs. failure)
      - dream3d:        integrations/dream3d_synthetic.py expert vs. basic
      - synthetic_conv: Claude-generated conversation quality pairs
      - physics:        Physics reasoning pairs (IOR, topology, etc.)
    """

    # Source file locations relative to the data directory (args.data_dir)
    SOURCE_FILES = {
        "execution": "execution_pairs.jsonl",
        "dream3d":   "dream3d_pairs.jsonl",
        "synthetic": "synthetic_conv_pairs.jsonl",
        "physics":   "physics_reasoning_pairs.jsonl",
    }

    def __init__(
        self,
        root: Path,
        sources: list[str],
        source_weights: Optional[dict[str, float]] = None,
        max_pairs: Optional[int] = None,
        val_split: float = 0.05,
        seed: int = 42,
    ):
        self.root    = root
        self.sources = sources
        self.weights = source_weights or {}
        self.val_split = val_split
        self.seed = seed

        self.all_pairs: list[dict] = []
        self._load_all(max_pairs)

    def _load_source(self, source: str) -> list[dict]:
        """Load one DPO source file."""
        rel_path = self.SOURCE_FILES.get(source)
        if not rel_path:
            log.warning(f"Unknown DPO source: {source}")
            return []

        path = self.root / rel_path
        if not path.exists():
            log.warning(f"DPO source not found: {path} (source={source})")
            log.warning(f"  Run generate_dpo_pairs.py to create this file.")
            return []

        pairs = []
        for line in path.read_text().splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                pair = json.loads(line)
            except json.JSONDecodeError:
                continue

            # Ensure required fields
            if not all(k in pair for k in ("prompt", "chosen", "rejected")):
                continue

            # Tag source and apply weight
            pair["source"] = pair.get("source", source)
            pair["weight"] = pair.get("weight", self.weights.get(source, 1.0))
            pairs.append(pair)

        log.info(f"  {source}: {len(pairs):,} pairs from {path.name}")
        return pairs

    def _load_all(self, max_pairs: Optional[int]):
        """Load and merge all sources."""
        for source in self.sources:
            self.all_pairs.extend(self._load_source(source))

        if not self.all_pairs:
            log.warning("No DPO pairs loaded. Check that data/dpo/*.jsonl files exist.")
            log.warning("Run generate_dpo_pairs.py to create them.")
            return

        random.seed(self.seed)
        random.shuffle(self.all_pairs)

        if max_pairs:
            self.all_pairs = self.all_pairs[:max_pairs]

        log.info(f"Total DPO pairs loaded: {len(self.all_pairs):,}")

    def _pair_to_hf(self, pair: dict) -> dict:
        """Convert to the format expected by TRL DPOTrainer."""
        return {
            "prompt":   pair["prompt"],
            "chosen":   pair["chosen"],
            "rejected": pair["rejected"],
        }

    def to_hf_datasets(self) -> tuple[Dataset, Dataset]:
        """Return (train_dataset, val_dataset) as HuggingFace Datasets."""
        if not self.all_pairs:
            empty = Dataset.from_list([])
            return empty, empty

        n_val = max(1, int(len(self.all_pairs) * self.val_split))
        val_pairs   = self.all_pairs[:n_val]
        train_pairs = self.all_pairs[n_val:]

        train_records = [self._pair_to_hf(p) for p in train_pairs]
        val_records   = [self._pair_to_hf(p) for p in val_pairs]

        return Dataset.from_list(train_records), Dataset.from_list(val_records)

    def source_stats(self) -> dict[str, int]:
        """Count pairs per source."""
        stats: dict[str, int] = {}
        for pair in self.all_pairs:
            src = pair.get("source", "unknown")
            stats[src] = stats.get(src, 0) + 1
        return stats


# ─── Callbacks ────────────────────────────────────────────────────────────────

class DPOMetricsCallback(TrainerCallback):
    """
    Logs DPO-specific metrics to console and W&B.

    Key metrics to watch:
      - rewards/chosen vs rewards/rejected: chosen should be consistently higher
      - logps/chosen vs logps/rejected: log probability of preferred responses
      - rewards/margins: chosen - rejected (higher = model more confidently prefers chosen)
    """

    def __init__(self, no_wandb: bool = False):
        self.no_wandb = no_wandb

    def on_log(self, args, state, control, logs=None, **kwargs):
        if not logs:
            return

        step = state.global_step
        loss = logs.get("loss", None)
        lr   = logs.get("learning_rate", None)

        # DPO-specific metrics
        reward_chosen   = logs.get("rewards/chosen", None)
        reward_rejected = logs.get("rewards/rejected", None)
        reward_margin   = logs.get("rewards/margins", None)
        reward_acc      = logs.get("rewards/accuracies", None)

        parts = [f"step {step:>5}"]
        if loss is not None:
            parts.append(f"loss {loss:.4f}")
        if reward_margin is not None:
            parts.append(f"margin {reward_margin:.3f}")
        if reward_acc is not None:
            parts.append(f"acc {reward_acc:.1%}")
        if lr is not None:
            parts.append(f"lr {lr:.2e}")

        log.info(" | ".join(parts))

        if HAS_WANDB and not self.no_wandb:
            wandb.log(logs, step=step)


class PerSourceEvalCallback(TrainerCallback):
    """
    Evaluates DPO loss separately per data source at each eval step.
    Useful for debugging which source is driving improvement.
    """

    def __init__(self, source_datasets: dict[str, Dataset], tokenizer, no_wandb: bool = False):
        self.source_datasets = source_datasets
        self.tokenizer = tokenizer
        self.no_wandb = no_wandb

    def on_evaluate(self, args, state, control, model=None, **kwargs):
        if not model or not self.source_datasets:
            return

        step = state.global_step
        log.info(f"Per-source evaluation at step {step}:")

        for source_name, dataset in self.source_datasets.items():
            if len(dataset) == 0:
                continue
            # Just log the counts for now — full per-source loss would require
            # a custom eval loop
            log.info(f"  {source_name}: {len(dataset):,} pairs available")


# ─── Evaluation ───────────────────────────────────────────────────────────────

@torch.no_grad()
def evaluate_execution_rate(
    model,
    tokenizer,
    val_prompts: list[dict],
    blender_path: Optional[str],
    n_eval: int = 50,
    max_new_tokens: int = 256,
    device: str = "cuda",
) -> dict:
    """
    Evaluate model on held-out prompts by actually executing the generated code in Blender.
    Returns:
      - execution_rate: fraction of generated scripts that run without error
      - scene_change_rate: fraction that cause a measurable scene change
    """
    if not blender_path or not val_prompts:
        return {}

    # Import reward function from train_rl.py
    try:
        from training.train_rl import NalanaRewardFunction, generate_completions, extract_blender_code, build_prompt_text
    except ImportError:
        log.warning("Could not import train_rl.py for eval — skipping execution rate eval")
        return {}

    reward_fn = NalanaRewardFunction(blender_path=blender_path, timeout=30, workers=4)
    model.eval()

    sample = random.sample(val_prompts, min(n_eval, len(val_prompts)))
    all_scores = []

    for prompt_data in sample:
        prompt_text = build_prompt_text(prompt_data, tokenizer)
        completions = generate_completions(
            model, tokenizer, prompt_text, n=1,
            max_new_tokens=max_new_tokens, temperature=0.3, device=device
        )
        if completions:
            code = extract_blender_code(completions[0])
            scores = reward_fn.score_batch([code])
            all_scores.extend(scores)

    if not all_scores:
        return {}

    return {
        "eval/execution_rate":    sum(1 for s in all_scores if s > 0.0) / len(all_scores),
        "eval/scene_change_rate": sum(1 for s in all_scores if s == 1.0) / len(all_scores),
        "eval/mean_reward":       sum(all_scores) / len(all_scores),
    }


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Stage 3: DPO training for Nalana conversation quality")

    # Model args
    parser.add_argument("--base-model", required=True,
                        help="Path to RL checkpoint (from train_rl.py), or SFT checkpoint")
    parser.add_argument("--ref-model", default=None,
                        help="Reference model for DPO KL penalty (defaults to --base-model)")
    parser.add_argument("--output-dir", default="checkpoints/nalana-dpo")
    parser.add_argument("--deepspeed", type=str, help="Path to DeepSpeed config JSON")
    parser.add_argument("--flash-attn", action="store_true", default=False)
    parser.add_argument("--lora-r", type=int, default=32)

    # Data args
    parser.add_argument("--data-dir", default="data/dpo",
                        help="Directory containing DPO pair files")
    parser.add_argument("--data-sources", nargs="+",
                        default=["execution", "dream3d", "synthetic", "physics"],
                        choices=["execution", "dream3d", "synthetic", "physics"],
                        help="Which DPO data sources to include")
    parser.add_argument("--data-weights", nargs="+", type=float, default=None,
                        help="Per-source loss weights (same order as --data-sources)")
    parser.add_argument("--max-pairs", type=int, default=None,
                        help="Cap total number of DPO pairs")
    parser.add_argument("--val-split", type=float, default=0.05)

    # DPO hyperparams
    parser.add_argument("--beta", type=float, default=0.1,
                        help="KL divergence strength. Higher = stay closer to reference. "
                             "0.1 is a good default. Lower (0.01) = more aggressive updates.")
    parser.add_argument("--loss-type", default="sigmoid",
                        choices=["sigmoid", "hinge", "ipo", "kto_pair"],
                        help="DPO loss variant. sigmoid = standard, ipo = conservative.")
    parser.add_argument("--label-smoothing", type=float, default=0.0,
                        help="Label smoothing for DPO loss (0.0-0.5)")
    parser.add_argument("--max-steps", type=int, default=1000)
    parser.add_argument("--batch-size", type=int, default=2,
                        help="Per-device batch size (DPO processes pairs, so effective is 2x)")
    parser.add_argument("--grad-accum", type=int, default=8)
    parser.add_argument("--learning-rate", type=float, default=5e-7,
                        help="DPO learning rate (very conservative — we're fine-tuning conversational style)")
    parser.add_argument("--max-length", type=int, default=2048,
                        help="Max sequence length for prompt + chosen/rejected")
    parser.add_argument("--max-prompt-length", type=int, default=1024)

    # Eval args
    parser.add_argument("--eval-steps", type=int, default=100)
    parser.add_argument("--eval-execution", action="store_true",
                        help="Run Blender execution eval on held-out set")
    parser.add_argument("--blender-path", type=str, default=None)
    parser.add_argument("--sft-data-dir", default="data/train",
                        help="SFT data dir (for execution rate eval prompts)")

    # Checkpoint args
    parser.add_argument("--save-steps", type=int, default=200)
    parser.add_argument("--save-total-limit", type=int, default=3)
    parser.add_argument("--warmup-steps", type=int, default=30)

    # Logging
    parser.add_argument("--no-wandb", action="store_true")
    parser.add_argument("--wandb-project", default="nalana-dpo")
    parser.add_argument("--wandb-run-name", default=None)

    args = parser.parse_args()

    if not HAS_TRL_DPO:
        log.error("TRL DPOTrainer not available. Install with: pip install trl>=0.11.0")
        return

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # ── W&B init ──────────────────────────────────────────────────────────────
    if HAS_WANDB and not args.no_wandb:
        wandb.init(
            project=args.wandb_project,
            name=args.wandb_run_name or f"nalana-dpo-{time.strftime('%Y%m%d-%H%M%S')}",
            config=vars(args),
        )
        log.info(f"W&B: {wandb.run.url}")

    # ── Load tokenizer ────────────────────────────────────────────────────────
    log.info(f"Loading tokenizer: {args.base_model}")
    tokenizer = AutoTokenizer.from_pretrained(args.base_model, trust_remote_code=True)
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    # ── Load model ────────────────────────────────────────────────────────────
    log.info(f"Loading policy model: {args.base_model}")
    model_kwargs = dict(torch_dtype=torch.bfloat16, device_map=None)
    if args.flash_attn:
        model_kwargs["attn_implementation"] = "flash_attention_2"

    from peft import PeftModel
    from pathlib import Path as _Path

    sft_adapter_config = _Path(args.base_model) / "adapter_config.json"
    if sft_adapter_config.exists():
        import json as _json
        adapter_cfg = _json.loads(sft_adapter_config.read_text())
        base_name = adapter_cfg.get("base_model_name_or_path", "Qwen/Qwen2.5-Coder-7B-Instruct")
        base = AutoModelForCausalLM.from_pretrained(base_name, torch_dtype=torch.bfloat16, device_map=None)
        model = PeftModel.from_pretrained(base, args.base_model)
    else:
        model = AutoModelForCausalLM.from_pretrained(
            args.base_model, trust_remote_code=True, **model_kwargs
        )
    model.enable_input_require_grads()

    # LoRA for DPO (conservative — we're adjusting style, not relearning ops)
    lora_cfg = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=args.lora_r,
        lora_alpha=args.lora_r * 2,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                         "gate_proj", "up_proj", "down_proj"],
        lora_dropout=0.05,
        bias="none",
    )
    model = get_peft_model(model, lora_cfg)
    model.print_trainable_parameters()

    # ── Load reference model (frozen) ─────────────────────────────────────────
    # The reference is what we used as input — prevents KL drift destroying
    # the Blender execution skills learned in SFT and RL stages.
    ref_model_path = args.ref_model or args.base_model
    log.info(f"Loading reference model (frozen): {ref_model_path}")
    ref_model = AutoModelForCausalLM.from_pretrained(
        ref_model_path, trust_remote_code=True, **model_kwargs
    )
    ref_model.eval()
    for param in ref_model.parameters():
        param.requires_grad_(False)

    # ── Load DPO data ─────────────────────────────────────────────────────────
    data_dir = Path(args.data_dir)
    log.info(f"\nLoading DPO pairs from: {data_dir}")
    log.info(f"  Sources: {args.data_sources}")

    # Build source → weight mapping
    source_weights = {}
    if args.data_weights and len(args.data_weights) == len(args.data_sources):
        for src, w in zip(args.data_sources, args.data_weights):
            source_weights[src] = w
    else:
        # Defaults: execution pairs are most reliable, so weight higher
        source_weights = {
            "execution": 1.5,   # Hard execution signal — very reliable
            "dream3d":   1.2,   # Expert 3D knowledge pairs
            "synthetic": 0.8,   # Synthetic conv pairs (lower confidence)
            "physics":   1.0,   # Physics reasoning pairs
        }

    dpo_data = DPODataset(
        root=data_dir,
        sources=args.data_sources,
        source_weights=source_weights,
        max_pairs=args.max_pairs,
        val_split=args.val_split,
    )

    source_stats = dpo_data.source_stats()
    log.info(f"\nDPO data breakdown:")
    for src, count in source_stats.items():
        weight = source_weights.get(src, 1.0)
        log.info(f"  {src:20s}: {count:,} pairs (weight={weight})")

    train_dataset, val_dataset = dpo_data.to_hf_datasets()
    log.info(f"\nTrain: {len(train_dataset):,} | Val: {len(val_dataset):,}")

    if len(train_dataset) == 0:
        log.error(
            "No training data found. Run generate_dpo_pairs.py first:\n"
            "  python generate_dpo_pairs.py --model checkpoints/nalana-rl/final\n"
            "Then re-run train_dpo.py."
        )
        return

    # Save args
    (output_dir / "args.json").write_text(json.dumps(vars(args), indent=2))
    (output_dir / "source_stats.json").write_text(json.dumps(source_stats, indent=2))

    # ── Training arguments ────────────────────────────────────────────────────
    n_gpus = torch.cuda.device_count() or 1
    effective_batch = args.batch_size * args.grad_accum * n_gpus

    steps_per_epoch = math.ceil(len(train_dataset) / effective_batch)
    total_steps = min(args.max_steps, steps_per_epoch * 3)  # max 3 epochs

    log.info(f"\nTraining config:")
    log.info(f"  GPUs: {n_gpus}")
    log.info(f"  Effective batch size: {effective_batch}")
    log.info(f"  Steps: {total_steps:,}")
    log.info(f"  Beta: {args.beta} | Loss: {args.loss_type}")
    log.info(f"  LR: {args.learning_rate:.2e}")

    # Use DPOConfig (TRL >= 0.12) or fall back to TrainingArguments
    try:
        from trl import DPOConfig as _DPOConfig
        training_args = _DPOConfig(
            output_dir=str(output_dir),
            max_steps=total_steps,
            per_device_train_batch_size=args.batch_size,
            per_device_eval_batch_size=args.batch_size,
            gradient_accumulation_steps=args.grad_accum,
            gradient_checkpointing=True,
            learning_rate=args.learning_rate,
            lr_scheduler_type="cosine",
            warmup_steps=args.warmup_steps,
            weight_decay=0.0,
            bf16=True,
            fp16=False,
            logging_steps=10,
            eval_strategy="steps",
            eval_steps=args.eval_steps,
            save_strategy="steps",
            save_steps=args.save_steps,
            save_total_limit=args.save_total_limit,
            load_best_model_at_end=True,
            metric_for_best_model="eval_rewards/margins",
            greater_is_better=True,
            report_to=[],  # We handle W&B via callback
            dataloader_num_workers=4,
            remove_unused_columns=False,
            deepspeed=args.deepspeed,
            # DPO-specific
            beta=args.beta,
            loss_type=args.loss_type,
            label_smoothing=args.label_smoothing,
            max_length=args.max_length,
            max_prompt_length=args.max_prompt_length,
        )
    except (TypeError, ImportError):
        # Older TRL: pass DPO params separately to DPOTrainer
        training_args = TrainingArguments(
            output_dir=str(output_dir),
            max_steps=total_steps,
            per_device_train_batch_size=args.batch_size,
            per_device_eval_batch_size=args.batch_size,
            gradient_accumulation_steps=args.grad_accum,
            gradient_checkpointing=True,
            learning_rate=args.learning_rate,
            lr_scheduler_type="cosine",
            warmup_steps=args.warmup_steps,
            weight_decay=0.0,
            bf16=True,
            fp16=False,
            logging_steps=10,
            eval_strategy="steps",
            eval_steps=args.eval_steps,
            save_strategy="steps",
            save_steps=args.save_steps,
            save_total_limit=args.save_total_limit,
            load_best_model_at_end=True,
            report_to=[],
            dataloader_num_workers=4,
            remove_unused_columns=False,
            deepspeed=args.deepspeed,
        )

    # ── Callbacks ─────────────────────────────────────────────────────────────
    callbacks = [DPOMetricsCallback(no_wandb=args.no_wandb)]

    # ── DPO Trainer ───────────────────────────────────────────────────────────
    dpo_trainer_kwargs = dict(
        model=model,
        ref_model=ref_model,
        processing_class=tokenizer,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        callbacks=callbacks,
    )

    # Handle both old and new TRL DPOTrainer API
    try:
        # TRL >= 0.12: pass DPOConfig as args
        trainer = DPOTrainer(args=training_args, **dpo_trainer_kwargs)
    except TypeError:
        # TRL < 0.12: pass TrainingArguments + explicit beta
        trainer = DPOTrainer(
            args=training_args,
            beta=args.beta,
            loss_type=args.loss_type,
            max_length=args.max_length,
            max_prompt_length=args.max_prompt_length,
            label_smoothing=args.label_smoothing,
            **dpo_trainer_kwargs,
        )

    # ── Train ─────────────────────────────────────────────────────────────────
    log.info(f"\nStarting DPO training → {output_dir}")
    trainer.train()
    trainer.save_model(str(Path(args.output_dir) / "dpo_adapter"))
    tokenizer.save_pretrained(str(Path(args.output_dir) / "dpo_adapter"))

    # ── Final execution rate eval ─────────────────────────────────────────────
    if args.eval_execution and args.blender_path:
        log.info("\nRunning post-training execution rate evaluation...")
        try:
            from training.train_rl import load_rl_prompts

            val_prompts = load_rl_prompts(Path(args.sft_data_dir), limit=200)
            exec_metrics = evaluate_execution_rate(
                model=model,
                tokenizer=tokenizer,
                val_prompts=val_prompts,
                blender_path=args.blender_path,
                n_eval=50,
            )
            if exec_metrics:
                log.info("Execution rate evaluation:")
                for k, v in exec_metrics.items():
                    log.info(f"  {k}: {v:.3f}")
                if HAS_WANDB and not args.no_wandb:
                    wandb.log(exec_metrics)
        except Exception as e:
            log.warning(f"Execution rate eval failed: {e}")

    # ── Save final model ──────────────────────────────────────────────────────
    final_dir = output_dir / "final"
    final_dir.mkdir(parents=True, exist_ok=True)

    log.info(f"\nMerging LoRA weights → {final_dir}")
    try:
        merged = model.merge_and_unload()
        merged.save_pretrained(str(final_dir))
    except Exception:
        model.save_pretrained(str(final_dir))

    tokenizer.save_pretrained(str(final_dir))

    if HAS_WANDB and not args.no_wandb:
        wandb.finish()

    log.info(f"\nDPO training complete.")
    log.info(f"  Final model: {final_dir}")
    log.info(f"\nSelf-improvement loop:")
    log.info(f"  python generate_dpo_pairs.py --model {final_dir} --output-dir data/dpo/round2")
    log.info(f"  python train_dpo.py --base-model {final_dir} --data-dir data/dpo/round2")


if __name__ == "__main__":
    main()
